export const L_KO = {
  manipSpec: "기본 정보",
  manipPosition: "위치 및 방향 설정",
  manipMass: "물리속성",
  manipCollaborationToggleLabel: "협동 운전 여부",
  manipCollaborationLabel: "협동 운전 모드",
  manipPhysRobotSize: "로봇 크기 (mm)",
  manipPhysMaxReach: "최대 리치 (mm)",
  manipPhysJointCount: "회전 관절 수 (개)",
  manipPhysRobotMass: "로봇 무게 (kg)",
  manipPhysPayload: "가반 하중 (kg)",
  manipPhysCurrentLoad: "현재 부하 무게 (kg)",
  safetySection: "안전 등급/인증",
  safetyPl: "안전 등급 (PL)",
  safetyCategory: "카테고리",
  safetySil: "안전 등급 (SIL)",
  safetyCertStatus: "인증 현황",
  safetyCertSpecs: "인증 제원 (정지•속도)",
  safetyLogicTitle: "Safety Logic 개요",
  safetyApplied: "적용 상태",
  badgeApplied: "적용됨",
  badgeNotApplied: "미적용",
  safetyMonitor: "모니터링",
  safetyMonitorPick: "상태 선택",
  safetyLastVerify: "마지막 검증",
  stopPerfTitle: "정지 성능 (분석 핵심)",
  stopTsLabel: "정지 시간 TS",
  stopSsLabel: "정지 거리 SS",
  stopPerfHint: "SSM / PFL 평가에 직접 반영되는 지표입니다.",
  responseDelayLabel: "반응 지연",
  measureLabel: "측정",
  certCustomPh: "직접 입력 또는 목록 추가",
  certApplyBtn: "적용",
  safetyStopTime: "로봇 정지 시간 (sec)",
  safetyTcpLimit: "TCP 제한 속도 (mm/sec)",
  connLinkedList: "연결 정보 상세",
  connColName: "객체명",
  connColModel: "모델",
  connColKind: "종류",
  connListEmpty: "연결된 객체가 없습니다.",
  connLinkedController: "연결된 제어기",
  connLinkedAuxAxis: "연결된 부가축",
  connLinkedCell: "연결된 셀",
  connLinkedEstop: "연결된 비상정지 스위치",
  connLinkedGrippers: "연결된 그리퍼",
  connNone: "NONE",
  criPrefix: "CRI",
  criSafe: "안전",
  criRisk: "위험",
  badgeAnalyzed: "분석완료",
  badgePending: "미분석",
  badgeCollab: "협동운전",
  badgeNoCollab: "비협동",
  badgeFree: "무료 로봇",
  badgePaid: "유료 로봇",
  /** CategoryMenu 접힘(호버 아님) 시 그립 아래 힌트 */
  categoryMenuCollapsedEdit: "Edit",
  eeToolInfo: "도구 정보",
  motionPath: "경로 설정",
  motionSpeed: "속도 설정",
  motionUploadSectionTitle: "모션 파일 업로드",
  motionFileUploadBtn: "모션 파일 업로드",
  motionFileListEmpty: "등록된 파일이 없습니다.",
  motionSequenceListTitle: "모션 리스트",
  motionSequenceEmpty: "등록된 모션이 없습니다.",
  /** 모션 서브모달(카테고리 우측): 리스트에서 항목 미선택 */
  motionSubmodalTitleDefaults: "모션 생성 기본값 설정",
  /** 모션 서브모달: 리스트에서 항목 선택 시 */
  motionSubmodalTitleEdit: "모션 수정",
  motionSubmodalBadgeEdit: "Edit",
  motionAddMoveSectionTitle: "이동 모션 기본값",
  motionAddMoveSectionHint: "모션 리스트에 ‘이동(Move)’ 행을 새로 추가할 때 아래 설정이 초기값으로 적용됩니다.",
  motionAddStopSectionTitle: "정지 모션 기본값",
  motionAddStopSectionHint: "모션 리스트에 ‘정지(Wait)’ 행을 새로 추가할 때 아래 정지 시간이 초기값으로 적용됩니다.",
  motionSubmodalDefaultsIntro: "이 패널의 값은 이후 새로 넣는 모션 행에만 반영됩니다. 이미 추가된 행은 바뀌지 않습니다.",
  motionJointDetailAccordionTitle: "조인트별 상세 설정",
  motionTcpSectionTitle: "TCP 위치·자세",
  motionTcpPositionRow: "위치 (mm)",
  motionTcpOrientationRow: "자세 (deg)",
  motionTcpAxisXmm: "X",
  motionTcpAxisYmm: "Y",
  motionTcpAxisZmm: "Z",
  motionTcpAxisRx: "Rx",
  motionTcpAxisRy: "Ry",
  motionTcpAxisRz: "Rz",
  motionFunctionLabel: "모션 함수 및 기본 설정",
  motionFunctionMoveL: "Move L",
  motionFunctionMoveJ: "Move J",
  speedBasisLabel: "속도 기준",
  speedBasisTime: "시간 기준",
  speedBasisSpeed: "속도 기준",
  motionAddAngularSpeedDeg: "각속도 (deg/sec)",
  motionAddAngularAccelDeg: "각가속도 (deg/sec²)",
  motionAddLinearSpeedMm: "각속도 (mm/sec)",
  motionAddLinearAccelMm: "가속도 (mm/sec²)",
  motionAddTimeSecLabel: "시간 (sec)",
  motionAddStopTimeLabel: "정지 시간 (sec)",
  motionSubmodalEditFormPlaceholder: "선택한 항목을 찾을 수 없습니다.",
  motionAddTcpSectionTitle: "TCP 기본값",
  motionAddTcpSectionHint:
    "모션 리스트에 새 ‘이동(Move)’ 행을 추가할 때 아래 TCP가 초기값으로 적용됩니다.",
  motionEditMoveSectionTitle: "이동 모션",
  motionEditMoveSectionHint: "이동 모션의 기본 설정을 변경",
  motionEditTcpSectionHint: "TCP가 위치할 좌표 및 각도 변경",
  motionEditTcpReadonlyHint: "정지(Wait) 구간에서는 TCP를 변경할 수 없습니다.",
  motionEditStopSectionTitle: "정지 모션",
  motionEditStopSectionHint: "선택한 정지 모션 행에만 적용되는 값입니다.",
  motionListWaypointPrefix: "Waypoint",
  motionListWaitTimeLabel: "Wait Time",
  motionListTotalLabel: "Total",
  motionKindMove: "이동",
  motionKindStop: "정지",
  tooltipAddMoveMotion: "이동 모션을 시퀀스에 추가합니다. 항목마다 MoveL / MoveJ가 번갈아 적용됩니다.",
  tooltipAddStopMotion: "정지 모션을 시퀀스에 추가합니다.",
  handGuidingMode: "핸드가이딩 모드",
  toolChangeBtn: "Tool-Change",
  toolChangeTooltip: "엔드이펙터 툴 교체 모드",
  motionAddEnter: "모션 추가(Enter)",
  handGuidingExit: "모드 종료",
  motionGenerateEmptyHint: "경로·속도 등 고급 설정은 우측 보조 패널에서 편집합니다.",
  motionUploadFile: "모션 파일",
  motionUploadSubmodalTitleDefault: "모션 파일 업로드",
  motionUploadSubmodalTitleReadonly: "업로드 모션 정보",
  motionUploadSubmodalBadgeReadonly: "조회 전용",
  motionUploadReadonlyFileLabel: "파일",
  motionUploadReadonlyMotionDurationLabel: "모션 시간",
  motionUploadReadonlyWaypointLabel: "웨이포인트",
  motionUploadReadonlyTimecodeLabel: "타임코드",
  motionUploadHint:
    "외부에서 생성한 모션(예: CSV·전용 포맷)을 업로드하면 이후 검증·적용에 사용할 수 있습니다.",
  collisionZone: "충돌 예상 영역",
  collisionRobotListTitle: "로봇 리스트",
  collisionRobotSelectedPrefix: "로봇",
  collisionRobotExpectedAreasTitle: "로봇 충돌 예상 부위",
  collisionEeListTitle: "엔드 이펙터 리스트",
  collisionEeExpectedAreasTitle: "엔드 이펙터 충돌 예상 부위",
  collisionEeSelectedPrefix: "엔드 이펙터",
  collisionAxisListTitle: "부가축 리스트",
  collisionAxisExpectedAreasTitle: "부가축 충돌 예상 부위",
  collisionAxisSelectedPrefix: "부가축",
  collisionWorkpieceListTitle: "작업대상물 리스트",
  collisionWorkpieceExpectedAreasTitle: "작업대상물 충돌 예상 부위",
  collisionWorkpieceSelectedPrefix: "작업대상물",
  collisionAreasRefreshAria: "목록 새로고침",
  collisionAreasCollapseAria: "목록 접기",
  collisionAreasCloseAria: "목록 닫기",
  collisionExpectedAreasShowAgain: "충돌 예상 부위 다시 표시",
  collisionContinuousGenerationModeBtn: "연속 생성 모드",
  collisionContinuousGenerationEndBtn: "연속 생성 모드 종료",
  collisionShapeSectionTitle: "형상 정보",
  collisionDimRadius: "반지름[mm]",
  collisionDimHeight: "높이[mm]",
  collisionDimFillet: "필렛[mm]",
  collisionDimSize: "사이즈",
  collisionDimHeightPlain: "높이",
  collisionDimRadiusPlain: "반지름",
  collisionDimRadiusHint: "구면의 반경 기준 치수입니다.",
  collisionDimHeightHint: "원통의 높이 방향 치수입니다.",
  collisionDimSizeHint: "큐브의 한 변 또는 대표 길이입니다.",
  collisionPoseSectionTitle: "생성할 위치",
  collisionGripperGen: "그리퍼에서 형상 생성",
  collisionGripperVertices: "그리퍼 버텍스 표시",
  collisionGripperWireframe: "그리퍼 와이어프레임 표시",
  collisionGripperEnlarge: "그리퍼에서 형상 생성 시 그리퍼 확대",
  collisionSoftCover: "소프트커버 적용",
  collisionSoftCoverSafety: "소프트커버 안전분석 추천",
  collisionSubmodalTitleDefaults: "기본값 설정",
  collisionSubmodalTitleEdit: "충돌 예상 부위 편집",
  collisionSubmodalBadgeDefaults: "기본값",
  collisionSubmodalBadgeEdit: "편집",
  collisionSubmodalPlaceholderOther: "이 카테고리는 우측 패널에서 설정합니다.",
  collisionSubmodalDefaultsIntro:
    "이 패널의 값은 이후 새로 추가하는 충돌 예상 부위에만 초기값으로 반영됩니다. 이미 추가된 부위는 바뀌지 않습니다.",
  collisionPoseDefaultsHint:
    "새로 추가하는 충돌 예상 부위에 공통으로 적용될 위치·자세 기본값입니다. 목록에서 부위를 선택하면 해당 항목만 따로 편집할 수 있습니다.",
  collisionShapeDefaultsHint: "새로 추가하는 충돌 예상 부위에 공통으로 적용될 형상·치수 기본값입니다.",
  collisionPoseEditHint: "선택한 충돌 예상 부위에만 적용됩니다.",
  collisionShapeEditHint: "선택한 충돌 예상 부위에만 적용됩니다.",
  collisionSubmodalEditIntro: "선택한 부위의 설정만 바뀝니다.",
  collisionAreaFocusRobotAria: "로봇에 초점",
  collisionAreaVisibilityAria: "가시성 전환",
  collisionDet: "감지 설정",
  collabArea: "협동 작업 영역",
  collabSafety: "협동 안전 설정",
  collabDefaultsSectionTitle: "기본 생성 설정",
  collabSubmodalTitle: "협동 작업 영역 기본값 설정",
  collabPositionSection: "협동작업공간 위치",
  collabSizeSection: "협동작업공간 크기",
  collabBodyPartSection: "충돌 예상 신체 부위",
  collabClothingThickness: "피복 두께 설정",
  collabWorkerDirection: "작업자 방향 설정",
  collabInfoTooltipClothing: "작업자 보호구·피복 두께를 반영합니다.",
  collabInfoTooltipWorkerDir: "작업자가 바라보는 방향 기준으로 영역을 둡니다.",
  collabCreateBtn: "협동작업영역 생성",
  collabAssignFromExistingBtn: "기존 항목에서 할당",
  collabAssignFromExistingHideBtn: "기존 항목 목록 닫기",
  collabExistingAssignListTitle: "기존 협동 작업 영역",
  collabLinkedToItemsLabel: "연결 항목",
  collabLinkedToItemsEmpty: "연결 항목 없음",
  collabSharedListTitle: "할당된 협동 작업 영역",
  collabUnassignedListTitle: "생성된 협동 작업 영역",
  collabAssignedSectionHint: "현재 선택된 객체에 연결된 협동 작업 영역입니다.",
  collabLibrarySectionHint: "프로젝트에 정의된 영역입니다. + 로 이 객체에 연결하거나 이름을 눌러 편집합니다.",
  collabSharedRobotsSection: "공유된 로봇",
  collabRobotNameCol: "로봇 이름",
  collabSelectAllRobots: "전체",
  collabColorModalTitle: "협동작업공간 색상 설정",
  collabColorChange: "색상 변경",
  collabOpacityLabel: "불투명도",
  collabEditModalCloseAria: "편집 닫기",
  collabColorModalCloseAria: "색상 설정 닫기",
  collabOpenColorPickerAria: "색상 팔레트 열기",
  collabMmUnit: "[mm]",
  collabVisibilityAria: "영역 표시 전환",
  collabAssignAria: "로봇 그룹에 할당",
  collabUnassignAria: "할당 해제",
  manipRobotType: "로봇 유형",
  manipRobotTypeSystemHint: "시스템에서 부여한 값입니다. 수정할 수 없습니다.",
  manipObjectName: "객체 이름",
  manipModel: "모델명",
  manipMaker: "제조사",
  manipPayload: "페이로드 (kg)",
  manipReach: "최대 도달 거리 (mm)",
  positionMm: "위치 (mm)",
  directionDeg: "방향 (deg)",
  sizeMm: "크기 (mm)",
  mass: "질량 (kg)",
  autoCoM: "Auto CoM",
  autoCoMTooltip: "무게중심을 자동으로 계산합니다",
  weightCoMMm: "무게중심 (mm)",
  eeListTitle: "엔드이펙터 리스트",
  eeSlotEmpty: "비어있음",
  eeFillInOrderHint: "순서대로 추가해 주세요! 앞 슬롯을 먼저 채워 주세요.",
  eeObjectName: "객체 이름",
  eeRemoveFromList: "리스트에서 삭제",
  panelEeDetailTitle: "엔드 이펙터 상세 설정",
  panelManipulatorDetailTitle: "로봇 상세 설정",
  manipListTitle: "로봇 리스트",
  manipListPanelSubtitle: "로봇을 선택하세요",
  manipListHintSingle: "선택된 객체에 결합된 로봇 리스트가 1개입니다. 현재 단일 항목만 출력됩니다.",
  manipListHintMultiple: "선택된 객체에 결합된 로봇 리스트가 여러 개입니다. 모든 결합 항목이 리스트에 출력됩니다.",
  manipListSingleItemTag: "단일 항목",
  manipListCombinedItemTag: "결합 항목",
  manipAddBindingBtn: "결합 추가",
  manipAddBindingHint: "결합 구조를 추가하는 버튼입니다. 현재는 UI 제안 단계로 기능은 연결되지 않았습니다.",
  manipSubTabDetail: "로봇 상세",
  manipSubTabSafety: "안전 정보",
  manipSubTabConn: "연결 정보",
  panelResizeTopAria: "패널 상단에서 높이 조절",
  panelResizeBottomAria: "패널 하단에서 높이 조절",
  eeSelectModel: "모델 선택",
  eeConnEmptySlotHint: "해당 슬롯에는 설치된 엔드이펙터가 없습니다.",
  eeModalTitle: "엔드 이펙터 모델 선택",
  eeModalDesc:
    "씬에 올라가는 그리퍼 메시입니다. 라이브러리에서 선택하거나 사용자 파일을 추가할 수 있습니다.",
  eeMakerPrefix: "제조사",
  eeMakerOnRobot: "OnRobot",
  eeMakerSchunk: "Schunk",
  eeMakerCustom: "사용자 커스텀",
  eeModalCustomHint:
    "STL·STEP·OBJ 등 사용자 메시를 추가합니다. + 버튼을 누르거나 아래에서 파일을 선택하세요.",
  eeModalUploadedListTitle: "업로드한 파일",
  eeModalCloseAria: "닫기",
  eeModalAddFile: "사용자 파일 추가",
  eeModalUpload: "Upload",
  eeModalChooseFile: "파일 선택",
  eeDetail: "도구 상세",
  eeType: "도구 유형",
  eeName: "도구 이름",
  eeMass: "도구 질량 (kg)",
  eeTcpSectionTitle: "설치 위치 및 크기",
  eeObjectSize: "객체 크기 (mm)",
  eeOuterDiam: "외경 (mm)",
  tcpPosition: "TCP 위치 (설치 위치, mm)",
  tcpDirection: "TCP 방향 (deg)",
  pathType: "경로 유형",
  blendRadius: "블렌딩 반경 (mm)",
  maxSpeed: "최대 속도 (mm/s)",
  acceleration: "가속도 (mm/s²)",
  jerk: "저크 (mm/s³)",
  zoneShape: "영역 형태",
  zoneRadius: "반경 (mm)",
  zoneHeight: "높이 (mm)",
  sensitivity: "감지 민감도",
  responseType: "반응 유형",
  areaWidth: "너비 (mm)",
  areaDepth: "깊이 (mm)",
  areaHeight: "높이 (mm)",
  pflActive: "PFL 활성화",
  ssmActive: "SSM 활성화",
  minSepDist: "최소 이격 거리 (mm)",
  safeSpeed: "안전 속도 (mm/s)",
  apply: "적용하기",
  subModalSectionTitle: "상세 설정",
  subModalPlaceholder:
    "고급 매개변수와 보조 입력을 이 패널에 배치할 수 있습니다. 화면 밖으로 나가면 위치가 자동으로 맞춰집니다.",
  subModalRelatedTabs: "관련 탭",
  langSwitchAria: "언어 전환",
  pointPaletteLegacyTitle: "기존 (객체별 색)",
  pointPaletteUnifiedTitle: "통일 (#FF8E2B)",
  pointPaletteHint: "적용할 포인트 팔레트입니다. 기존은 다색, 통일은 주황·검정 계열입니다.",
  pointPaletteApply: "적용 중",
  langCurrentKo: "한국어",
  langCurrentEn: "English",
} as const;

export type AppLabels = { [K in keyof typeof L_KO]: string };

/** UI 전체 영문 (키는 L_KO와 동일) */
export const L_EN: AppLabels = {
  manipSpec: "Basic info",
  manipPosition: "Position & orientation settings",
  manipMass: "Physical properties",
  manipCollaborationToggleLabel: "Collaborative driving enabled",
  manipCollaborationLabel: "Collaborative driving mode",
  manipPhysRobotSize: "Robot size (mm)",
  manipPhysMaxReach: "Max reach (mm)",
  manipPhysJointCount: "Revolute joints (count)",
  manipPhysRobotMass: "Robot mass (kg)",
  manipPhysPayload: "Payload capacity (kg)",
  manipPhysCurrentLoad: "Current load (kg)",
  safetySection: "Safety rating / certification",
  safetyPl: "Performance Level (PL)",
  safetyCategory: "Category",
  safetySil: "SIL rating",
  safetyCertStatus: "Certification status",
  safetyCertSpecs: "Certified limits (stop • speed)",
  safetyLogicTitle: "Safety Logic overview",
  safetyApplied: "Applied",
  badgeApplied: "Applied",
  badgeNotApplied: "Not applied",
  safetyMonitor: "Monitoring",
  safetyMonitorPick: "Select state",
  safetyLastVerify: "Last verification",
  stopPerfTitle: "Stop performance (analysis)",
  stopTsLabel: "Stop time TS",
  stopSsLabel: "Stop distance SS",
  stopPerfHint: "Directly reflected in SSM / PFL evaluation.",
  responseDelayLabel: "Response delay",
  measureLabel: "Measure",
  certCustomPh: "Enter or add from list",
  certApplyBtn: "Apply",
  safetyStopTime: "Robot stop time (sec)",
  safetyTcpLimit: "TCP limit speed (mm/sec)",
  connLinkedList: "Connection details",
  connColName: "Name",
  connColModel: "Model",
  connColKind: "Type",
  connListEmpty: "No linked objects.",
  connLinkedController: "Linked controller",
  connLinkedAuxAxis: "Linked auxiliary axis",
  connLinkedCell: "Linked cell",
  connLinkedEstop: "Linked emergency stop",
  connLinkedGrippers: "Linked grippers",
  connNone: "NONE",
  criPrefix: "CRI",
  criSafe: "Safe",
  criRisk: "Risk",
  badgeAnalyzed: "Analyzed",
  badgePending: "Pending",
  badgeCollab: "Collaborative",
  badgeNoCollab: "Non-collab",
  badgeFree: "Free robot",
  badgePaid: "Paid robot",
  categoryMenuCollapsedEdit: "Edit",
  eeToolInfo: "Tool info",
  motionPath: "Path",
  motionSpeed: "Speed",
  motionUploadSectionTitle: "Motion file upload",
  motionFileUploadBtn: "Upload motion file",
  motionFileListEmpty: "No files registered.",
  motionSequenceListTitle: "Motion list",
  motionSequenceEmpty: "No motions registered.",
  motionSubmodalTitleDefaults: "Default motion creation",
  motionSubmodalTitleEdit: "Edit motion",
  motionSubmodalBadgeEdit: "Edit",
  motionAddMoveSectionTitle: "Default move motion",
  motionAddMoveSectionHint:
    "These values are used as defaults when you add a new Move row to the motion list.",
  motionAddStopSectionTitle: "Default stop motion",
  motionAddStopSectionHint:
    "This stop duration is used as the default when you add a new Wait row.",
  motionSubmodalDefaultsIntro:
    "Values here apply only to newly added motion rows. Existing rows are not changed.",
  motionJointDetailAccordionTitle: "Per-joint detail",
  motionTcpSectionTitle: "TCP position & orientation",
  motionTcpPositionRow: "Position (mm)",
  motionTcpOrientationRow: "Orientation (deg)",
  motionTcpAxisXmm: "X",
  motionTcpAxisYmm: "Y",
  motionTcpAxisZmm: "Z",
  motionTcpAxisRx: "Rx",
  motionTcpAxisRy: "Ry",
  motionTcpAxisRz: "Rz",
  motionFunctionLabel: "Motion function & defaults",
  motionFunctionMoveL: "Move L",
  motionFunctionMoveJ: "Move J",
  speedBasisLabel: "Speed mode",
  speedBasisTime: "Time-based",
  speedBasisSpeed: "Speed-based",
  motionAddAngularSpeedDeg: "Angular speed (deg/sec)",
  motionAddAngularAccelDeg: "Angular accel (deg/sec²)",
  motionAddLinearSpeedMm: "Linear speed (mm/sec)",
  motionAddLinearAccelMm: "Linear accel (mm/sec²)",
  motionAddTimeSecLabel: "Time (sec)",
  motionAddStopTimeLabel: "Stop time (sec)",
  motionSubmodalEditFormPlaceholder: "Selected item could not be found.",
  motionAddTcpSectionTitle: "Default TCP",
  motionAddTcpSectionHint:
    "These TCP values are used as defaults when you add a new Move row.",
  motionEditMoveSectionTitle: "Move motion",
  motionEditMoveSectionHint: "Change default settings for move motion.",
  motionEditTcpSectionHint: "Change TCP position and orientation.",
  motionEditTcpReadonlyHint: "TCP cannot be edited during Wait.",
  motionEditStopSectionTitle: "Stop motion",
  motionEditStopSectionHint: "Values apply only to the selected stop row.",
  motionListWaypointPrefix: "Waypoint",
  motionListWaitTimeLabel: "Wait Time",
  motionListTotalLabel: "Total",
  motionKindMove: "Move",
  motionKindStop: "Stop",
  tooltipAddMoveMotion: "Add a move to the sequence. MoveL / MoveJ alternate per item.",
  tooltipAddStopMotion: "Add a stop to the sequence.",
  handGuidingMode: "Hand guiding mode",
  toolChangeBtn: "Tool-Change",
  toolChangeTooltip: "End-effector tool change mode",
  motionAddEnter: "Add motion (Enter)",
  handGuidingExit: "Exit mode",
  motionGenerateEmptyHint: "Edit path, speed, etc. in the side panel.",
  motionUploadFile: "Motion file",
  motionUploadSubmodalTitleDefault: "Motion file upload",
  motionUploadSubmodalTitleReadonly: "Uploaded motion info",
  motionUploadSubmodalBadgeReadonly: "Read-only",
  motionUploadReadonlyFileLabel: "File",
  motionUploadReadonlyMotionDurationLabel: "Motion duration",
  motionUploadReadonlyWaypointLabel: "Waypoint",
  motionUploadReadonlyTimecodeLabel: "Timecode",
  motionUploadHint:
    "Upload externally created motions (CSV, proprietary formats, etc.) for validation and use.",
  collisionZone: "Collision zone",
  collisionRobotListTitle: "Robot list",
  collisionRobotSelectedPrefix: "Robot",
  collisionRobotExpectedAreasTitle: "Robot collision expected areas",
  collisionEeListTitle: "End effector list",
  collisionEeExpectedAreasTitle: "End effector collision expected areas",
  collisionEeSelectedPrefix: "End effector",
  collisionAxisListTitle: "Additional axis list",
  collisionAxisExpectedAreasTitle: "Additional axis collision expected areas",
  collisionAxisSelectedPrefix: "Additional axis",
  collisionWorkpieceListTitle: "Workpiece list",
  collisionWorkpieceExpectedAreasTitle: "Workpiece collision expected areas",
  collisionWorkpieceSelectedPrefix: "Workpiece",
  collisionAreasRefreshAria: "Refresh list",
  collisionAreasCollapseAria: "Collapse list",
  collisionAreasCloseAria: "Close list",
  collisionExpectedAreasShowAgain: "Show collision expected areas again",
  collisionContinuousGenerationModeBtn: "Continuous generation mode",
  collisionContinuousGenerationEndBtn: "Exit continuous generation mode",
  collisionShapeSectionTitle: "Shape information",
  collisionDimRadius: "Radius [mm]",
  collisionDimHeight: "Height [mm]",
  collisionDimFillet: "Fillet [mm]",
  collisionDimSize: "Size",
  collisionDimHeightPlain: "Height",
  collisionDimRadiusPlain: "Radius",
  collisionDimRadiusHint: "Radius of the spherical surface.",
  collisionDimHeightHint: "Extrusion height of the cylinder.",
  collisionDimSizeHint: "Cube edge length or representative size.",
  collisionPoseSectionTitle: "Placement",
  collisionGripperGen: "Generate shape from gripper",
  collisionGripperVertices: "Show gripper vertices",
  collisionGripperWireframe: "Show gripper wireframe",
  collisionGripperEnlarge: "Enlarge gripper when generating shape from gripper",
  collisionSoftCover: "Apply soft cover",
  collisionSoftCoverSafety: "Soft-cover safety analysis",
  collisionSubmodalTitleDefaults: "Default settings",
  collisionSubmodalTitleEdit: "Edit collision expected area",
  collisionSubmodalBadgeDefaults: "Default",
  collisionSubmodalBadgeEdit: "Edit",
  collisionSubmodalPlaceholderOther: "Configure this category in the property panel.",
  collisionSubmodalDefaultsIntro:
    "These values apply as defaults only when you add new collision expected areas. Existing areas are not changed.",
  collisionPoseDefaultsHint:
    "Default placement and orientation for newly added expected areas. Select an area in the list to edit that item only.",
  collisionShapeDefaultsHint: "Default primitive and dimensions for newly added collision expected areas.",
  collisionPoseEditHint: "Applies only to the selected expected area.",
  collisionShapeEditHint: "Applies only to the selected expected area.",
  collisionSubmodalEditIntro: "Only the selected area is updated.",
  collisionAreaFocusRobotAria: "Focus on robot",
  collisionAreaVisibilityAria: "Toggle visibility",
  collisionDet: "Detection",
  collabArea: "Collaborative area",
  collabSafety: "Collaborative safety",
  collabDefaultsSectionTitle: "Default creation settings",
  collabSubmodalTitle: "Collaborative workspace default settings",
  collabPositionSection: "Workspace position",
  collabSizeSection: "Workspace size",
  collabBodyPartSection: "Expected body part for collision",
  collabClothingThickness: "Clothing thickness",
  collabWorkerDirection: "Operator direction",
  collabInfoTooltipClothing: "Include protective equipment / clothing thickness.",
  collabInfoTooltipWorkerDir: "Orient the zone relative to the operator facing direction.",
  collabCreateBtn: "Create collaborative workspace",
  collabAssignFromExistingBtn: "Assign from existing",
  collabAssignFromExistingHideBtn: "Hide existing list",
  collabExistingAssignListTitle: "Existing collaborative workspaces",
  collabLinkedToItemsLabel: "Linked items",
  collabLinkedToItemsEmpty: "No linked items",
  collabSharedListTitle: "Assigned to this object",
  collabUnassignedListTitle: "Project workspaces",
  collabAssignedSectionHint: "Workspaces linked to the currently selected object.",
  collabLibrarySectionHint: "All workspaces in this project. Use + to link one to this object, or tap the name to edit.",
  collabSharedRobotsSection: "Shared robots",
  collabRobotNameCol: "Robot name",
  collabSelectAllRobots: "All",
  collabColorModalTitle: "Workspace color",
  collabColorChange: "Color",
  collabOpacityLabel: "Opacity",
  collabEditModalCloseAria: "Close editor",
  collabColorModalCloseAria: "Close color settings",
  collabOpenColorPickerAria: "Open color palette",
  collabMmUnit: "[mm]",
  collabVisibilityAria: "Toggle visibility",
  collabAssignAria: "Assign to robot group",
  collabUnassignAria: "Unassign",
  manipRobotType: "Robot type",
  manipRobotTypeSystemHint: "Assigned by the system. Cannot be edited.",
  manipObjectName: "Object name",
  manipModel: "Model",
  manipMaker: "Manufacturer",
  manipPayload: "Payload (kg)",
  manipReach: "Max reach (mm)",
  positionMm: "Position (mm)",
  directionDeg: "Orientation (deg)",
  sizeMm: "Size (mm)",
  mass: "Mass (kg)",
  autoCoM: "Auto CoM",
  autoCoMTooltip: "Compute center of mass automatically",
  weightCoMMm: "Center of mass (mm)",
  eeListTitle: "End effector list",
  eeSlotEmpty: "Empty",
  eeFillInOrderHint: "Add slots in order. Fill the earlier slots first.",
  eeObjectName: "Object name",
  eeRemoveFromList: "Remove from list",
  panelEeDetailTitle: "End effector detail",
  panelManipulatorDetailTitle: "Robot detail settings",
  manipListTitle: "Robot list",
  manipListPanelSubtitle: "Select a robot",
  manipListHintSingle: "One robot is currently bound to the selected object. Only a single item is shown.",
  manipListHintMultiple: "Multiple robots are bound to the selected object. All bound items are listed.",
  manipListSingleItemTag: "Single item",
  manipListCombinedItemTag: "Bound item",
  manipAddBindingBtn: "Add binding",
  manipAddBindingHint: "Adds a new binding structure. This is currently a UX proposal button with no wired behavior yet.",
  manipSubTabDetail: "Robot detail",
  manipSubTabSafety: "Safety",
  manipSubTabConn: "Connections",
  panelResizeTopAria: "Resize panel height from the top",
  panelResizeBottomAria: "Resize panel height from the bottom",
  eeSelectModel: "Select model",
  eeConnEmptySlotHint: "No end effector installed in this slot.",
  eeModalTitle: "Select end effector model",
  eeModalDesc:
    "Gripper mesh in the scene. Pick from the library or add your own file.",
  eeMakerPrefix: "Maker",
  eeMakerOnRobot: "OnRobot",
  eeMakerSchunk: "Schunk",
  eeMakerCustom: "Custom",
  eeModalCustomHint:
    "Add user mesh (STL, STEP, OBJ, etc.). Use + or choose a file below.",
  eeModalUploadedListTitle: "Uploaded files",
  eeModalCloseAria: "Close",
  eeModalAddFile: "Add custom file",
  eeModalUpload: "Upload",
  eeModalChooseFile: "Choose file",
  eeDetail: "Tool detail",
  eeType: "Tool type",
  eeName: "Tool name",
  eeMass: "Tool mass (kg)",
  eeTcpSectionTitle: "Mount position & size",
  eeObjectSize: "Object size (mm)",
  eeOuterDiam: "Outer diameter (mm)",
  tcpPosition: "TCP position (mount, mm)",
  tcpDirection: "TCP orientation (deg)",
  pathType: "Path type",
  blendRadius: "Blend radius (mm)",
  maxSpeed: "Max speed (mm/s)",
  acceleration: "Acceleration (mm/s²)",
  jerk: "Jerk (mm/s³)",
  zoneShape: "Zone shape",
  zoneRadius: "Radius (mm)",
  zoneHeight: "Height (mm)",
  sensitivity: "Sensitivity",
  responseType: "Response type",
  areaWidth: "Width (mm)",
  areaDepth: "Depth (mm)",
  areaHeight: "Height (mm)",
  pflActive: "PFL enabled",
  ssmActive: "SSM enabled",
  minSepDist: "Minimum separation (mm)",
  safeSpeed: "Safe speed (mm/s)",
  apply: "Apply",
  subModalSectionTitle: "Detail",
  subModalPlaceholder:
    "Place advanced parameters here. Position adjusts if the panel goes off-screen.",
  subModalRelatedTabs: "Related tabs",
  langSwitchAria: "Switch language",
  pointPaletteLegacyTitle: "Legacy (per-object)",
  pointPaletteUnifiedTitle: "Unified (#FF8E2B)",
  pointPaletteHint: "Choose the accent palette. Legacy uses multiple colors; unified uses orange and black tones.",
  pointPaletteApply: "Active",
  langCurrentKo: "한국어",
  langCurrentEn: "English",
};

/** 기본 export: 한국어 (기존 import `L` 호환) */
export const L: AppLabels = L_KO as unknown as AppLabels;
